services:
  app:
      image: php:8.0-fpm
      container_name: app
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
      depends_on:
        - database

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetmagic
      # If you want to use a different user, uncomment these lines
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Change the host port to 3307

    volumes:
      - database_data:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      # SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      SERVER_NAME: "127.0.0.1:8000"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
  ###< symfony/mercure-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
  ###< symfony/mercure-bundle ###
