controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# config/routes.yaml
chat:
    path: /chat/{id}
    controller: App\Controller\ChatController::chat
    requirements:
        id: \d+

app_qr_code:
    path: /qr-code/{slug}
    controller: App\Controller\QrCodeController::generateQrCode
    methods: GET